version: '3.7'
services:
  bitcoind:
    image: lncm/bitcoind:v0.18.1
    entrypoint: bitcoind
    volumes:
      - /media/noma/bitcoind:/root/.bitcoin
      - /media/noma/bitcoind:/datadir
    restart: on-failure
    network_mode: host

  lnd:
    image: lncm/lnd:0.7.1-experimental-watchtower-neutrino
    volumes:
      - /media/noma/lnd/fullnode:/root/.lnd
      - /media/noma/lnd/fullnode/lnd.conf:/home/lncm/.lnd/lnd.conf
    restart: on-failure
    network_mode: host

  invoicer:
    image: lncm/invoicer:v0.6.2
    volumes:
      - /media/noma/invoicer:/root/.lncm
      - /media/noma/lnd/fullnode:/lnd
      - /media/noma/public_html:/static
      - /media/noma/invoicer:/logs
    depends_on:
      - bitcoind
      - lnd
    restart: on-failure
    network_mode: host
